### ISSUE TITLE
Can we get a 0.2.0 tag?

### ISSUE THREAD

**Issue by stevenwadejr** [stevenmaguire/oauth2-salesforce#2]
I see that you've merged in the PR that adds a new `AccessToken` with access to the `instance_url` returned from Salesforce. Can you tag a new release so we can update from Composer to get this functionality?

**Comment by stevenmaguire** [comment]
@stevenwadejr Wow! I apologize for that. It is very unlike me to merge some changes, update the changelog and then not cut a release. Thank you for the nudge. 0.2.0 is out.

**Comment by stevenwadejr** [comment]
No worries. Thanks for the tag!
