### ISSUE TITLE
How to connect to sandbox

### ISSUE THREAD

**Issue by ronnievisser** [stevenmaguire/oauth2-salesforce#3]
Hi,

I see production urls are hardcoded in the package. Is there a away to avoid this and to use a Salesforce sandbox (test.salesforce.com) instead?

Thanks

**Comment by stevenmaguire** [comment]
@RonnieVisser I've added #4 in response to this request. It appears that the only domain that is up for grabs here is the domain used for authentication. It is hard coded as `https://login.salesforce.com`. This update provides a getter and setter method, as well as an optional instantiation configuration key to set this value. Please review the PR and let me know if you feel this will address your concerns.

**Comment by stevenmaguire** [comment]
This functionality is now available in version 0.3.0 of this package.

**Comment by ronnievisser** [comment]
Perfect! I solved it to extend your package in a custom class. This is a way better solution so will upgrade the package to 0.3.0.

thanks!!
